### ISSUE TITLE
Ne fonctionne pas si on vient de la liste des favoris

### ISSUE THREAD

**Issue by psa-jforestier** [OptiPanda/lbc_old_price#1]
Super extension, je valide !

Mais j'ai remarqué un probleme : la différence de prix n'apparait pas quand on provient de la liste des annonces mises en favoris. Par contre cela fonctionne si on affiche l'annonce dans un nouvel onglet.
Bonus : si possible, faire apparaitre la différence de prix directement dans la liste des favoris.

**Comment by OptiPanda** [comment]
Salut !

Il faut que je test mais je pense que la page en provenant de la liste des favoris est issues du cache. Si tu fais un ctrl+f5 ça devrait fonctionner !

Pour ce qui est de mettre l'ancien prix directement sur les recherches / favoris c'est quelque chose que j'ai en tête mais sur lequel je n'ai pas encore pris le temps de me pencher !

Merci pour ton retour, hésite pas à me dire si le ctrl+f5 corrige le souci !

**Comment by psa-jforestier** [comment]
Merci pour le retour.
A priori, ce n'est pas un prb de cache : 
- démarrer une navigation privée
- aller sur LBC, accepter les cookies, se loguer
- aller sur la page des favoris
- repérer une annonce en baisse
- cliquer sur l'annonce
- la page affiche le prix actuel, la fleche, mais pas le prix original.

On constate la même chose quand on vient de la page des résultats de recherche : 
- repérer une annonce en baisse sur la liste des résultats
- cliquer sur l'annonce
- la page affiche le prix actuel, la fleche, mais pas le prix original.
- si on recharge la page (F5), la baisse de prix apparait

Ca doit etre lié au mode de chargement progressive-web-app de LBC, l'extension firefox a peut etre du mal a repéré le changement de page virtuelle.

**Comment by OptiPanda** [comment]
Effectivement je viens de reproduire, je vais regarder si je peux faire un event listener ou quelque chose du genre, merci pour le report.

Pour l'évol ça viendra après ! :D

**Comment by OptiPanda** [comment]
@psa-jforestier La nouvelle version contient l'évol ! :D
