### ISSUE TITLE
L'ancien prix n'apparait pas sur annonce professionnel

### ISSUE THREAD

**Issue by psa-jforestier** [OptiPanda/lbc_old_price#2]
J'ai remarque que sur une annonce de type "pro", l'ancien prix n'apparait pas, même apres rechargement, vidage du cache ect.
Un exemple : https://www.leboncoin.fr/informatique/2352766799.htm
Cela provient probablement du fait que la position du prix n'est pas au même endroit que sur les annonces des particuliers.

**Comment by OptiPanda** [comment]
Hello,

J'investiguerai là dessus dans la semaine, à première vue c'est parce que l'architecture de la page des pro est différente.

Merci pour le retour
